#pragma once

#include <iostream>
#include <vector>
#include <array>
#include <fstream>
#include <string>
#include <sstream>
#include <any>
#include <memory>
#include <cstdint>
#include <unordered_map>
#include <unordered_set>
#include <map>
#include <set>
#include <algorithm>
#include <functional>
#include <variant>
#include <utility>
#include <ranges>
#include <stdexcept>
#include <filesystem>