#pragma once

enum class TokenKind {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_BRACKET, RIGHT_BRACKET,
    PLUS, MINUS, STAR, SLASH, MODULO, POWER,
    BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL, IDENTIFIER, STRING, NUMBER, CHARACTER,

    IF, ELSE, TRUE, FALSE, AND, OR,
    NIL, RETURN, VAR, CONST, WHILE, FOR,
    FUNC, THIS, SUPER, CLASS, CONTINUE, BREAK,
    SWITCH, CASE, DEFAULT, DO, SEMICOLON,

    ERROR, END_OF_FILE
};